name: memverse
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.7.1=py313hfc0e8ea_100
  - annotated-types=0.6.0=py313h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - blas=1.0=mkl
  - boltons=24.1.0=py313h06a4308_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - brotli-python=1.0.9=py313h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.11.12=py313h06a4308_0
  - cffi=1.17.1=py313h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda=25.5.1=py313h06a4308_0
  - conda-anaconda-telemetry=0.1.2=py313h06a4308_1
  - conda-anaconda-tos=0.2.0=py313h06a4308_0
  - conda-content-trust=0.2.0=py313h06a4308_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313h06a4308_0
  - conda-package-streaming=0.11.0=py313h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=45.0.3=py313h2ccb017_0
  - distro=1.9.0=py313h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozendict=2.4.2=py313h06a4308_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - gobject-introspection=1.84.0=py313hcb37abf_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h78213b7_2
  - gtk2=2.24.33=h4ce724d_4
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - idna=3.7=py313h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jpeg=9e=h5eee18b_3
  - jsonpatch=1.33=py313h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libboost=1.82.0=h109eef0_2
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgd=2.3.3=h536bbd8_4
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py313hdb19cb5_1
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - librsvg=2.56.3=hb0330b6_2
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libtool=2.4.7=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py313h06a4308_1
  - mdurl=0.1.0=py313h06a4308_0
  - menuinst=2.2.0=py313h06a4308_1
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py313h5eee18b_2
  - mkl_fft=1.3.11=py313h5eee18b_0
  - mkl_random=1.2.8=py313h06d7b56_0
  - ncurses=6.4=h6a678d5_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=2.3.1=py313h8d96ed3_0
  - numpy-base=2.3.1=py313h8e760e0_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.17=h5eee18b_0
  - packaging=24.2=py313h06a4308_0
  - pango=1.50.7=h668f713_2
  - pcre2=10.42=hebb0a14_1
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.7=py313h06a4308_0
  - pluggy=1.5.0=py313h06a4308_0
  - poppler=24.09.0=hc52b300_2
  - poppler-data=0.4.11=h06a4308_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py313h06a4308_0
  - pydantic-core=2.27.1=py313h4aa5aa6_0
  - pygments=2.19.1=py313h06a4308_0
  - pysocks=1.7.1=py313h06a4308_0
  - python=3.13.5=h4612cfd_100_cp313
  - python-graphviz=0.20.1=py313h06a4308_1
  - python_abi=3.13=0_cp313
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py313h06a4308_1
  - rich=13.9.4=py313h06a4308_0
  - ruamel.yaml=0.18.10=py313h5eee18b_0
  - ruamel.yaml.clib=0.2.12=py313h5eee18b_0
  - setuptools=72.1.0=py313h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - spdlog=1.11.0=hdb19cb5_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h993c535_1
  - tqdm=4.67.1=py313h7040dfc_0
  - truststore=0.10.0=py313h06a4308_0
  - typing-extensions=4.12.2=py313h06a4308_0
  - typing_extensions=4.12.2=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.3.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py313h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - anyio==4.12.0
      - ascii-colors==0.11.4
      - dotenv==0.9.9
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - jiter==0.12.0
      - json-repair==0.54.2
      - nano-vectordb==0.0.4.3
      - networkx==3.6.1
      - openai==2.9.0
      - pipmaster==1.0.10
      - pypinyin==0.55.0
      - python-dotenv==1.2.1
      - regex==2025.11.3
      - sniffio==1.3.1
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - wcwidth==0.2.14
