name: memverse
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - av=9.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - expat=2.7.1
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - lz4-c=1.9.4
  - ncurses=6.4
  - nettle=3.6
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pthread-stubs=0.3
  - python=3.10.18
  - python_abi=3.10
  - readline=8.2
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - x264=1!161.3030
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - anthropic==0.58.2
      - anyio==3.7.1
      - argcomplete==1.10.3
      - ascii-colors==0.11.4
      - asn1crypto==1.5.1
      - async-timeout==5.0.1
      - attrdict==2.0.1
      - attrs==25.3.0
      - backoff==2.2.1
      - banks==2.2.0
      - beautifulsoup4==4.13.5
      - bert-score==0.3.13
      - binpacking==1.5.2
      - bitsandbytes==0.42.0
      - bleach==6.3.0
      - brotli==1.1.0
      - bs4==0.0.2
      - bson==0.5.10
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==1.17.1
      - chardet==3.0.4
      - charset-normalizer==3.4.3
      - click==8.2.1
      - clip==1.0
      - clip-interrogator==0.6.0
      - colorama==0.4.6
      - composio==0.8.0
      - composio-client==1.6.0
      - configparser==7.2.0
      - contourpy==1.3.2
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cryptography==45.0.6
      - cycler==0.12.1
      - dacite==1.9.2
      - dataclasses-json==0.6.7
      - datasets==3.3.2
      - defusedxml==0.7.1
      - demjson3==3.0.6
      - deprecated==1.2.18
      - dill==0.3.8
      - dirtyjson==1.0.8
      - diskcache==5.6.3
      - distro==1.9.0
      - docstring-parser==0.17.0
      - docx2txt==0.9
      - dotenv==0.9.9
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - ffmpeg==1.4
      - ffmpy==0.6.1
      - filelock==3.19.1
      - filetype==1.2.0
      - fonttools==4.59.1
      - frozenlist==1.7.0
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - future==1.0.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.178.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-genai==1.4.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - gradio==5.44.1
      - gradio-client==1.12.1
      - graphiti-core==0.18.5
      - greenlet==3.2.3
      - griffe==1.7.3
      - groovy==0.1.2
      - grpcio==1.73.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.35.0
      - humps==0.2.2
      - icrawler==0.6.10
      - idna==3.10
      - imageio==2.37.0
      - imapclient==2.1.0
      - importlib-metadata==8.7.0
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==0.10.0
      - joblib==1.5.1
      - json-repair==0.47.8
      - kaggle==1.7.4.5
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightrag-hku==1.4.7
      - llama-cloud==0.1.32
      - llama-cloud-services==0.6.43
      - llama-index==0.12.50
      - llama-index-agent-openai==0.4.12
      - llama-index-cli==0.4.4
      - llama-index-core==0.12.51
      - llama-index-embeddings-google-genai==0.2.0
      - llama-index-embeddings-openai==0.3.1
      - llama-index-indices-managed-llama-cloud==0.7.10
      - llama-index-instrumentation==0.3.0
      - llama-index-llms-openai==0.4.7
      - llama-index-multi-modal-llms-openai==0.5.3
      - llama-index-program-openai==0.3.2
      - llama-index-question-gen-openai==0.3.1
      - llama-index-readers-file==0.4.11
      - llama-index-readers-llama-parse==0.4.0
      - llama-index-workflows==1.1.0
      - llama-parse==0.6.43
      - lxml==6.0.0
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - modelscope==1.29.1
      - mpmath==1.3.0
      - ms-swift==3.7.2
      - multidict==6.6.3
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - nano-vectordb==0.0.4.3
      - neo4j==5.28.2
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - ollama==0.6.0
      - open-clip-torch==3.1.0
      - openai==1.97.0
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - opentelemetry-api==1.35.0
      - opentelemetry-exporter-otlp==1.35.0
      - opentelemetry-exporter-otlp-proto-common==1.35.0
      - opentelemetry-exporter-otlp-proto-grpc==1.35.0
      - opentelemetry-exporter-otlp-proto-http==1.35.0
      - opentelemetry-instrumentation==0.56b0
      - opentelemetry-instrumentation-requests==0.56b0
      - opentelemetry-proto==1.35.0
      - opentelemetry-sdk==1.35.0
      - opentelemetry-semantic-conventions==0.56b0
      - opentelemetry-util-http==0.56b0
      - orjson==3.11.3
      - oss2==2.19.1
      - packaging==25.0
      - pandas==2.2.3
      - pathvalidate==3.3.1
      - pdfminer-six==20191110
      - peft==0.17.1
      - pg8000==1.31.4
      - pgvector==0.4.1
      - pillow==11.3.0
      - pip==25.2
      - pipmaster==1.0.2
      - platformdirs==4.3.8
      - posthog==6.5.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pypdf==5.8.0
      - pypdf2==3.0.1
      - pypinyin==0.55.0
      - pysher==1.0.8
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - python-pptx==0.6.23
      - python-slugify==8.0.4
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - rank-bm25==0.2.2
      - rapidfuzz==3.13.0
      - regex==2025.9.1
      - requests==2.32.5
      - rich==14.1.0
      - rouge==1.0.1
      - rsa==4.9.1
      - ruff==0.12.11
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-image==0.19.3
      - scipy==1.15.3
      - scramp==1.4.6
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - setuptools==80.9.0
      - shellingham==1.5.4
      - simplejson==3.20.1
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - speechrecognition==3.14.3
      - sqlalchemy==2.0.41
      - starlette==0.47.3
      - striprtf==0.0.26
      - sympy==1.13.1
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - text-unidecode==1.3
      - tifffile==2025.5.10
      - tiktoken==0.11.0
      - timm==1.0.19
      - tokenizers==0.22.0
      - tomlkit==0.13.3
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.56.1
      - transformers-stream-generator==0.0.5
      - triton==3.2.0
      - trl==0.20.0
      - typer==0.16.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - tzlocal==5.3.1
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.24.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==14.2
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xlrd==1.2.0
      - xlsxwriter==3.2.5
      - xxhash==3.5.0
      - yarl==1.20.1
      - yt-dlp==2025.11.12
      - zipp==3.23.0
      - zstandard==0.24.0
